main = ".output/server/index.mjs"
compatibility_date = "2023-08-14"

[site]
bucket = ".output/public"

[env.prod]
name = "portfolio"
route = "erwan-jugand.fr/*"
workers_dev = false

[env.dev]
name = "portfolio-dev"
workers_dev = true
